debugging
debugging of the planetary data file, orbit propagator class and main script, still recieving one error regarding  line 7 "from orbit_propagator import_orbit propagator as OP" when file is ran it references system file:

 File "C:\Users\gary-\OneDrive\Documents\GitHub\GS-ME409\orbit_propagator.py", line 7
    class Orbit_propagator_class
                               ^
SyntaxError: invalid syntax

the code is still refeering to the old class/file name Orbit_propagator_class which was updated to orbit_propagator